apiVersion: v1
kind: Service
metadata:
  name: grpc-server-h2c-v1
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "grpc-backendconfig"}'
  labels:
    app: grpc-server-h2c
    version: v1
spec:
  type: ClusterIP
  selector:
    app: grpc-server-h2c
    version: v1
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
    appProtocol: HTTP2
