apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grpc-route-h2c
spec:
  parentRefs:
  - name: grpc-gateway-h2c
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grpc-server-h2c
      port: 50051
