apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grpc-route-tls
spec:
  parentRefs:
  - name: grpc-gateway-tls
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grpc-server-tls
      port: 50051
